# Generated by Django 3.1.7 on 2021-03-28 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userprofile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('taskid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('taskhead', models.TextField()),
                ('taskbody', models.TextField()),
                ('taskreminder', models.BooleanField(default=False)),
                ('taskauthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.userprofile')),
            ],
        ),
    ]
