# Generated by Django 3.1.7 on 2021-03-28 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userprofile',
            new_name='profile',
        ),
    ]
